[package]
name = "tmnt_wiki_bot_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.2"
argh = "0.1.9"
itertools = "0.10.5"
rayon = "1.6.1"
wikipedia = "0.3.4"
